apiVersion: v1
kind: Service
metadata:
  name: catalogo-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: logstash
      port: 12801
      targetPort: 12801
  selector:
    app: catalogo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-service
  labels:
    app: catalogo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo-service
  template:
    metadata:
      labels:
        app: catalogo-service
    spec:
      containers:
        - name: catalogo-service
          image: infnet-ms/catalogo-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
            - containerPort: 12801
