apiVersion: v1
kind: Service
metadata:
  name: cliente-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: cliente-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-service
  labels:
    app: cliente-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente-service
  template:
    metadata:
      labels:
        app: cliente-service
    spec:
      containers:
        - name: cliente-service
          image: infnet-ms/cliente-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
