apiVersion: v1
kind: Service
metadata:
  name: emprestimo-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: emprestimo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emprestimo-service
  labels:
    app: emprestimo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emprestimo-service
  template:
    metadata:
      labels:
        app: emprestimo-service
    spec:
      containers:
        - name: emprestimo-service
          image: infnet-ms/emprestimo-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
