spring:
  application:
    name: catalogo-service
  datasource:
    url: jdbc:h2:mem:catalogo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8083

eureka:
  instance:
    appname: catalogo-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
