name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      catalogo-changed: ${{ steps.catalogo.outputs.catalogo }}
      eureka-changed: ${{ steps.eureka.outputs.eureka }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if catalogo-service changed
        id: catalogo
        uses: dorny/paths-filter@v2
        with:
          filters: |
            catalogo:
              - 'catalogo-service/**'

      - name: Check if eureka-server changed
        id: eureka
        uses: dorny/paths-filter@v2
        with:
          filters: |
            eureka:
              - 'eureka-server/**'

  build-catalogo-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.catalogo-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test catalogo-service
        working-directory: catalogo-service
        run: mvn clean install

      - name: Upload catalogo-service artifact
        uses: actions/upload-artifact@v3
        with:
          name: catalogo-service
          path: catalogo-service/target/*.jar

  build-eureka-server:
    needs: detect-changes
    if: needs.detect-changes.outputs.eureka-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test eureka-server
        working-directory: eureka-server
        run: mvn clean install

      - name: Upload eureka-server artifact
        uses: actions/upload-artifact@v3
        with:
          name: eureka-server
          path: eureka-server/target/*.jar